# Generated by Django 4.0.6 on 2022-07-18 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_item_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
    ]
