# Generated by Django 4.0.6 on 2022-07-18 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_item_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
    ]
